/* Photography manifest — generated by tools/photos.py.
 *
 * Run  py -3 tools/photos.py  after adding files to img/Photography/.
 * Captions, album titles, blurbs and covers written here are preserved;
 * new photos arrive with a TODO caption for you to fill in.
 */

window.ALBUMS = [
    { id: "travel", title: "Travel", blurb: "Gotta go fast" },
    { id: "astro", title: "Astrophotography", blurb: "If only I didn't have to stay up so late" },
    { id: "aviation", title: "Aviation" },
    { id: "wildlife", title: "Wildlife", blurb: "Nature's uncooperative subjects" },
];

window.PHOTOS = [
    // Astrophotography
    {
        src: "img/Photography/Astro/composite.webp",
        alt: "Milky Way at Badlands National Park",
        album: "astro",
        w: 2000,
        h: 1579
    },
    // Wildlife
    {
        src: "img/Photography/Wildlife/NEB07331.webp",
        alt: "Icelandic Puffin coming in for a landing",
        album: "wildlife",
        w: 2000,
        h: 1333
    },
];

window.PHOTOS_FLICKR_URL = "https://www.flickr.com/photos/202301591@N02/albums/72177720324069259";
