#!/usr/bin/env python3
"""Regenerate js/photos-data.js from the folders under img/Photography/.

    py -3 tools/photos.py              scan, report, rewrite the manifest
    py -3 tools/photos.py --optimize   also convert/resize oversized images
    py -3 tools/photos.py --check      report only, write nothing

Folder name becomes the album: img/Photography/Night Sky/ -> id "night-sky",
title "Night Sky". Captions (`alt`), album titles, blurbs and covers you have
already written are preserved; only new photos come back needing a caption.

--optimize never deletes anything: the source file is moved to
img/Photography/_originals/ and the converted .webp is written in its place.
"""

import argparse
import json
import re
import shutil
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTO_DIR = ROOT / "img" / "Photography"
MANIFEST = ROOT / "js" / "photos-data.js"
ORIGINALS = PHOTO_DIR / "_originals"

READABLE = {".webp", ".jpg", ".jpeg", ".png", ".tif", ".tiff", ".bmp"}
MAX_EDGE = 2000
QUALITY = 82
NEEDS_CAPTION = "TODO: describe this photo"

FLICKR_DEFAULT = (
    "https://www.flickr.com/photos/202301591@N02/albums/72177720324069259"
)


def slugify(name):
    slug = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
    return slug or "album"


def parse_existing(text):
    """Recover album metadata and captions from the current manifest.

    Tolerant by design: it reads key/value pairs out of each object literal, so
    hand-edited captions, reordered keys and extra whitespace all survive.
    """
    albums, photos = [], {}

    def objects(array_name):
        m = re.search(
            r"window\.%s\s*=\s*\[(.*?)\n\];" % array_name, text, re.S
        )
        if not m:
            return []
        found = []
        for block in re.finditer(r"\{(.*?)\}", m.group(1), re.S):
            body = block.group(1)
            if body.lstrip().startswith("//"):
                continue
            entry = {}
            for key, raw in re.findall(
                r'(\w+)\s*:\s*("(?:[^"\\]|\\.)*"|\d+)', body
            ):
                entry[key] = json.loads(raw) if raw.startswith('"') else int(raw)
            if entry:
                found.append(entry)
        return found

    for entry in objects("ALBUMS"):
        if "id" in entry:
            albums.append(entry)
    for entry in objects("PHOTOS"):
        if "src" in entry:
            photos[entry["src"]] = entry
    return albums, photos


def optimize(path, max_edge, quality):
    """Convert to WebP and cap the long edge. Returns (new_path, note)."""
    from PIL import Image

    with Image.open(path) as im:
        im = im.convert("RGB") if im.mode not in ("RGB", "RGBA") else im
        width, height = im.size
        longest = max(width, height)
        already_webp = path.suffix.lower() == ".webp"

        if already_webp and longest <= max_edge:
            return path, None

        if longest > max_edge:
            scale = max_edge / longest
            new_size = (round(width * scale), round(height * scale))
            im = im.resize(new_size, Image.LANCZOS)
        else:
            new_size = (width, height)

        target = path.with_suffix(".webp")
        ORIGINALS.mkdir(parents=True, exist_ok=True)
        stash = ORIGINALS / path.name
        counter = 1
        while stash.exists():
            stash = ORIGINALS / f"{path.stem}-{counter}{path.suffix}"
            counter += 1

        if target.exists() and target != path:
            return path, f"skipped, {target.name} already exists"

        im.save(target, "WEBP", quality=quality, method=6)

    shutil.move(str(path), str(stash))
    note = f"{width}x{height} -> {new_size[0]}x{new_size[1]}"
    if path.suffix.lower() != ".webp":
        note += f", {path.suffix.lstrip('.')} -> webp"
    return target, note


def dimensions(path):
    from PIL import Image

    with Image.open(path) as im:
        return im.size


def js_string(value):
    return json.dumps(value, ensure_ascii=False)


def render(albums, photos, flickr_url):
    lines = [
        "/* Photography manifest — generated by tools/photos.py.",
        " *",
        " * Run  py -3 tools/photos.py  after adding files to img/Photography/.",
        " * Captions, album titles, blurbs and covers written here are preserved;",
        " * new photos arrive with a TODO caption for you to fill in.",
        " */",
        "",
        "window.ALBUMS = [",
    ]

    for album in albums:
        parts = ["id: " + js_string(album["id"]), "title: " + js_string(album["title"])]
        if album.get("blurb"):
            parts.append("blurb: " + js_string(album["blurb"]))
        if album.get("cover"):
            parts.append("cover: " + js_string(album["cover"]))
        lines.append("    { " + ", ".join(parts) + " },")

    lines += ["];", "", "window.PHOTOS = ["]

    by_album = {}
    for photo in photos:
        by_album.setdefault(photo["album"], []).append(photo)

    for album in albums:
        group = by_album.get(album["id"], [])
        if not group:
            continue
        lines.append("    // " + album["title"])
        for photo in group:
            lines.append("    {")
            lines.append("        src: " + js_string(photo["src"]) + ",")
            lines.append("        alt: " + js_string(photo["alt"]) + ",")
            lines.append("        album: " + js_string(photo["album"]) + ",")
            lines.append(f"        w: {photo['w']},")
            lines.append(f"        h: {photo['h']}")
            lines.append("    },")

    lines += [
        "];",
        "",
        "window.PHOTOS_FLICKR_URL = " + js_string(flickr_url) + ";",
        "",
    ]
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--optimize", action="store_true",
                        help="convert to WebP and cap the long edge")
    parser.add_argument("--check", action="store_true",
                        help="report only; do not write the manifest")
    parser.add_argument("--max-edge", type=int, default=MAX_EDGE)
    parser.add_argument("--quality", type=int, default=QUALITY)
    args = parser.parse_args()

    if not PHOTO_DIR.exists():
        sys.exit(f"No such folder: {PHOTO_DIR}")

    existing_albums, existing_photos = ([], {})
    flickr_url = FLICKR_DEFAULT
    if MANIFEST.exists():
        text = MANIFEST.read_text(encoding="utf-8")
        existing_albums, existing_photos = parse_existing(text)
        found = re.search(r'window\.PHOTOS_FLICKR_URL\s*=\s*"([^"]*)"', text)
        if found:
            flickr_url = found.group(1)

    # Match on the slug, not the literal id, so an album written by hand as
    # "Astro" still claims the Astro/ folder and keeps its title and blurb.
    known_album = {slugify(a["id"]): a for a in existing_albums}
    order = [slugify(a["id"]) for a in existing_albums]  # keep your ordering

    albums, photos = [], []
    added, optimized, skipped = [], [], []
    carried = set()  # entries that only changed extension, not identity

    folders = sorted(
        (p for p in PHOTO_DIR.iterdir() if p.is_dir() and not p.name.startswith("_")),
        key=lambda p: p.name.lower(),
    )

    for folder in folders:
        album_id = slugify(folder.name)
        album = dict(known_album.get(album_id, {"title": folder.name}))
        album["id"] = album_id
        album.setdefault("title", folder.name)

        files = sorted(
            (f for f in folder.iterdir() if f.is_file() and not f.name.startswith(".")),
            key=lambda f: f.name.lower(),
        )

        entries = []
        for path in files:
            if path.suffix.lower() not in READABLE:
                skipped.append(f"{path.relative_to(ROOT)} (unsupported type)")
                continue

            # Optimizing can change the extension, which would orphan the
            # caption written against the old filename — so look the entry up
            # under both names.
            former_src = path.relative_to(ROOT).as_posix()

            if args.optimize and not args.check:
                try:
                    path, note = optimize(path, args.max_edge, args.quality)
                    if note:
                        optimized.append(f"{path.relative_to(ROOT)}: {note}")
                except Exception as exc:  # keep going; report at the end
                    skipped.append(f"{path.relative_to(ROOT)} ({exc})")
                    continue

            try:
                width, height = dimensions(path)
            except Exception as exc:
                skipped.append(f"{path.relative_to(ROOT)} ({exc})")
                continue

            src = path.relative_to(ROOT).as_posix()
            prior = existing_photos.get(src)
            if prior is None:
                prior = existing_photos.get(former_src)
                if prior is not None:
                    carried.add(former_src)
            alt = prior.get("alt") if prior else None
            if not alt or alt == NEEDS_CAPTION:
                if not prior:
                    added.append(src)
                alt = alt or NEEDS_CAPTION

            entries.append({"src": src, "alt": alt, "album": album_id,
                            "w": width, "h": height})

        if not entries:
            continue

        # A cover that no longer exists would silently fall back; drop it.
        if album.get("cover") and album["cover"] not in {e["src"] for e in entries}:
            if not (ROOT / album["cover"]).exists():
                album.pop("cover")

        albums.append(album)
        photos.extend(entries)

    # An album you declared but haven't filled yet keeps its title and blurb,
    # so making the folder later is all that's needed. It renders nothing until
    # it has photos.
    have = {a["id"] for a in albums}
    empty = []
    for slug, album in known_album.items():
        if slug in have:
            continue
        kept = dict(album)
        kept["id"] = slug
        albums.append(kept)
        empty.append(f'{kept["title"]} (expected img/Photography/{kept["title"]}/)')

    albums.sort(key=lambda a: order.index(a["id"]) if a["id"] in order else len(order))

    gone = sorted(set(existing_photos) - {p["src"] for p in photos} - carried)

    if optimized:
        print(f"Optimized {len(optimized)}:")
        for line in optimized:
            print("  " + line)
    if added:
        print(f"\nNew photos needing a caption ({len(added)}):")
        for line in added:
            print("  " + line)
    if gone:
        print(f"\nNo longer on disk, dropped from the manifest ({len(gone)}):")
        for line in gone:
            print("  " + line)
    if empty:
        print(f"\nDeclared with no folder yet, kept ({len(empty)}):")
        for line in empty:
            print("  " + line)
    if skipped:
        print(f"\nSkipped ({len(skipped)}):")
        for line in skipped:
            print("  " + line)

    print(f"\n{len(albums)} album(s), {len(photos)} photo(s).")

    todo = sum(1 for p in photos if p["alt"] == NEEDS_CAPTION)
    if todo:
        print(f"{todo} still need a caption — search js/photos-data.js for TODO.")

    if args.check:
        print("\n--check: manifest not written.")
        return

    MANIFEST.parent.mkdir(parents=True, exist_ok=True)
    MANIFEST.write_text(render(albums, photos, flickr_url), encoding="utf-8")
    print(f"Wrote {MANIFEST.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
